# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - r12_arm_controller
    - hand_controller

  r12_arm_controller:
    type: FollowJointTrajectory
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - hand_joint
      - wrist_joint
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - gripper_joint
    action_ns: gripper_cmd
    default: true